[package]
name = "v_flakes"
version = "0.1.1"
edition = "2024"
authors = ["Valeriy Sakharov <valeratrades@gmail.com>"]
description = "CLI tools for v_flakes nix module management"
license = "BlueOak-1.0.0"
repository = "https://github.com/valeratrades/v_flakes"

[package.metadata]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[dependencies]
clap = { version = "4", features = ["derive"] }
toml_edit = "0.25"

[dev-dependencies]
v_fixtures = { path = "/home/v/s/v_fixtures" }
